Traceback (most recent call last):
  File "/home/ws/fq0795/git/gnn_uncertainty/datasets/helper/cv_visualizer.py", line 346, in <module>
    get_al_animation("al/run69/data/train/")
  File "/home/ws/fq0795/git/gnn_uncertainty/datasets/helper/cv_visualizer.py", line 327, in get_al_animation
    paths.extend(
    ^^^^^
UnboundLocalError: cannot access local variable 'paths' where it is not associated with a value
